import json
import os
import sys

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from neo4j_client import kg_client

def run():
    print("Extracting graph data from MasterKG for Next.js UI...")
    
    # 1. Fetch Patients (Limit 200 for UI performance)
    print("Fetching Patients...")
    patients_data = kg_client.execute_query("""
        MATCH (p:Patient)
        RETURN p.rid AS id, labels(p)[0] AS type, 'Patient ' + p.rid AS label, p AS properties
        LIMIT 200
    """)
    
    # 2. Fetch Ontology Nodes
    print("Fetching Ontology Nodes...")
    ontology_data = kg_client.execute_query("""
        MATCH (n)
        WHERE NOT 'Patient' IN labels(n)
        RETURN elementId(n) AS id, labels(n)[0] AS type, n.name AS label, n AS properties
        LIMIT 50
    """)
    
    nodes = []
    
    # Process Patients
    patient_ids = set()
    for row in patients_data:
        patient_ids.add(str(row['id']))
        props = row['properties']
        node = {
            "id": f"patient-{row['id']}",
            "type": "Patient",
            "label": f"RID-{row['id']}",
            "properties": {
                "rid": props.get("rid", ""),
                "diagnosis": props.get("baseline_diagnosis", props.get("terminal_diagnosis", "Unknown")),
                "mmse": props.get("mmse_baseline", 0),
                "age": props.get("age", 0)
            }
        }
        nodes.append(node)
        
    # Process Ontology
    ontology_id_map = {}
    for row in ontology_data:
        original_id = row['id']
        t = row['type']
        label = row['label'] or t
        new_id = f"{t.lower()}-{original_id}"
        ontology_id_map[original_id] = new_id
        
        node = {
            "id": new_id,
            "type": t,
            "label": label,
            "properties": row['properties']
        }
        nodes.append(node)

    # 3. Fetch SIMILAR_TO Edges
    print("Fetching Patient Edges...")
    patient_edges_data = kg_client.execute_query("""
        MATCH (p1:Patient)-[r:SIMILAR_TO]->(p2:Patient)
        RETURN p1.rid AS source, p2.rid AS target, r.euclidean_distance AS weight, elementId(r) AS edge_id
        LIMIT 300
    """)
    
    edges = []
    for row in patient_edges_data:
        if str(row['source']) in patient_ids and str(row['target']) in patient_ids:
            edges.append({
                "id": f"edge-{row['edge_id']}",
                "source": f"patient-{row['source']}",
                "target": f"patient-{row['target']}",
                "type": "SIMILAR_TO",
                "properties": {
                    "weight": row['weight'] if row['weight'] is not None else 0.5,
                    "strength": "strong" if (row['weight'] is not None and row['weight'] < 0.1) else "medium"
                }
            })
            
    # 4. Fetch Ontology Edges
    print("Fetching Ontology Edges...")
    onto_edges_data = kg_client.execute_query("""
        MATCH (n1)-[r]->(n2)
        WHERE NOT 'Patient' IN labels(n1) AND NOT 'Patient' IN labels(n2)
        RETURN elementId(n1) AS source, elementId(n2) AS target, type(r) AS edge_type, elementId(r) AS edge_id
        LIMIT 100
    """)
    
    for row in onto_edges_data:
        s = row['source']
        t = row['target']
        if s in ontology_id_map and t in ontology_id_map:
            edges.append({
                "id": f"edge-{row['edge_id']}",
                "source": ontology_id_map[s],
                "target": ontology_id_map[t],
                "type": row['edge_type'],
                "properties": {
                    "strength": "strong"
                }
            })

    # Add random coordinates for the graph layout engine to start from
    import random
    import math
    for i, node in enumerate(nodes):
        node['x'] = random.randint(100, 700)
        node['y'] = random.randint(100, 500)

    # Write to furi-graph-data.ts
    out_path = os.path.join(os.path.dirname(__file__), '..', 'UI', 'new_temp', 'lib', 'furi-graph-data.ts')
    
    ts_content = f"""// AUTO-GENERATED BY sync_ui_graph.py
import type {{ GraphData }} from './types';

export const mockGraphData: GraphData = {json.dumps({"nodes": nodes, "edges": edges}, indent=2)};
"""
    with open(out_path, 'w') as f:
        f.write(ts_content)
        
    print(f"Successfully exported {len(nodes)} nodes and {len(edges)} edges to {out_path}!")

if __name__ == '__main__':
    run()
